[tool.poetry]
name = "test2"
version = "0.1.0"
description = ""
authors = ["revh2 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "^2.14.3"
environs = "^9.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
